name: Deploy to Server Staging

on:
  push:
    branches:
      - main  # Hanya trigger ketika ada push ke branch main

jobs:
  deploy-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main  # Gunakan branch main

      - name: Deploy to Staging via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SS_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/html/ozapi
            
            # Fetch semua perubahan dari remote
            git fetch origin
            
            # Reset branch main ke versi remote
            git checkout main
            git reset --hard origin/main
            
            # Install dependencies (tanpa dev dependencies)
            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
            
            # Run database migrations
            php artisan migrate --force
            
            # Cache optimizations
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            
            # Jika menggunakan frontend build
            # npm ci --production
            # npm run build
            
            # Reload PHP jika diperlukan
            # sudo systemctl reload php-fpm